# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\GitHub_repo\DEV_pymel\00_wip\SmartRig\ManageCtrls\manageCtrls_ui.ui'
#
# Created: Mon May 11 15:39:24 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(170, 106)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.move_grp = QtGui.QGroupBox(Form)
        self.move_grp.setObjectName("move_grp")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.move_grp)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(self.move_grp)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Xminus_pb = QtGui.QPushButton(self.groupBox_2)
        self.Xminus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Xminus_pb.setObjectName("Xminus_pb")
        self.horizontalLayout.addWidget(self.Xminus_pb)
        self.Xplus_pb = QtGui.QPushButton(self.groupBox_2)
        self.Xplus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Xplus_pb.setObjectName("Xplus_pb")
        self.horizontalLayout.addWidget(self.Xplus_pb)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.move_grp)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Yminus_pb = QtGui.QPushButton(self.groupBox_3)
        self.Yminus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Yminus_pb.setObjectName("Yminus_pb")
        self.horizontalLayout_2.addWidget(self.Yminus_pb)
        self.Yplus_pb = QtGui.QPushButton(self.groupBox_3)
        self.Yplus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Yplus_pb.setObjectName("Yplus_pb")
        self.horizontalLayout_2.addWidget(self.Yplus_pb)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.move_grp)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Zminus_pb = QtGui.QPushButton(self.groupBox_4)
        self.Zminus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Zminus_pb.setObjectName("Zminus_pb")
        self.horizontalLayout_3.addWidget(self.Zminus_pb)
        self.Zplus_pb = QtGui.QPushButton(self.groupBox_4)
        self.Zplus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Zplus_pb.setObjectName("Zplus_pb")
        self.horizontalLayout_3.addWidget(self.Zplus_pb)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addWidget(self.move_grp)
        self.scaleGrp = QtGui.QGroupBox(Form)
        self.scaleGrp.setObjectName("scaleGrp")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.scaleGrp)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scaleXYZGrp = QtGui.QGroupBox(self.scaleGrp)
        self.scaleXYZGrp.setObjectName("scaleXYZGrp")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.scaleXYZGrp)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.scaleXYZ_minus_pb = QtGui.QPushButton(self.scaleXYZGrp)
        self.scaleXYZ_minus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleXYZ_minus_pb.setObjectName("scaleXYZ_minus_pb")
        self.horizontalLayout_6.addWidget(self.scaleXYZ_minus_pb)
        self.scaleXYZ_plus_pb = QtGui.QPushButton(self.scaleXYZGrp)
        self.scaleXYZ_plus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleXYZ_plus_pb.setObjectName("scaleXYZ_plus_pb")
        self.horizontalLayout_6.addWidget(self.scaleXYZ_plus_pb)
        self.horizontalLayout_5.addWidget(self.scaleXYZGrp)
        self.scaleXGrp = QtGui.QGroupBox(self.scaleGrp)
        self.scaleXGrp.setObjectName("scaleXGrp")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.scaleXGrp)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.scaleX_minus_pb = QtGui.QPushButton(self.scaleXGrp)
        self.scaleX_minus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleX_minus_pb.setObjectName("scaleX_minus_pb")
        self.horizontalLayout_7.addWidget(self.scaleX_minus_pb)
        self.scaleX_plus_pb = QtGui.QPushButton(self.scaleXGrp)
        self.scaleX_plus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleX_plus_pb.setObjectName("scaleX_plus_pb")
        self.horizontalLayout_7.addWidget(self.scaleX_plus_pb)
        self.horizontalLayout_5.addWidget(self.scaleXGrp)
        self.scaleYGrp = QtGui.QGroupBox(self.scaleGrp)
        self.scaleYGrp.setObjectName("scaleYGrp")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.scaleYGrp)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.scaleY_minus_pb = QtGui.QPushButton(self.scaleYGrp)
        self.scaleY_minus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleY_minus_pb.setObjectName("scaleY_minus_pb")
        self.horizontalLayout_8.addWidget(self.scaleY_minus_pb)
        self.scaleY_plus_pb = QtGui.QPushButton(self.scaleYGrp)
        self.scaleY_plus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleY_plus_pb.setObjectName("scaleY_plus_pb")
        self.horizontalLayout_8.addWidget(self.scaleY_plus_pb)
        self.horizontalLayout_5.addWidget(self.scaleYGrp)
        self.scaleZGrp = QtGui.QGroupBox(self.scaleGrp)
        self.scaleZGrp.setObjectName("scaleZGrp")
        self.horizontalLayout_9 = QtGui.QHBoxLayout(self.scaleZGrp)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.scaleZ_minus_pb = QtGui.QPushButton(self.scaleZGrp)
        self.scaleZ_minus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleZ_minus_pb.setObjectName("scaleZ_minus_pb")
        self.horizontalLayout_9.addWidget(self.scaleZ_minus_pb)
        self.scaleZ_plus_pb = QtGui.QPushButton(self.scaleZGrp)
        self.scaleZ_plus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.scaleZ_plus_pb.setObjectName("scaleZ_plus_pb")
        self.horizontalLayout_9.addWidget(self.scaleZ_plus_pb)
        self.horizontalLayout_5.addWidget(self.scaleZGrp)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.scaleGrp)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Controllers Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.move_grp.setTitle(QtGui.QApplication.translate("Form", "Move:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.Xminus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Xplus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.Yminus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Yplus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.Zminus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Zplus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleGrp.setTitle(QtGui.QApplication.translate("Form", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXYZGrp.setTitle(QtGui.QApplication.translate("Form", "XYZ:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXYZ_minus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXYZ_plus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXGrp.setTitle(QtGui.QApplication.translate("Form", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleX_minus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleX_plus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleYGrp.setTitle(QtGui.QApplication.translate("Form", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleY_minus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleY_plus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleZGrp.setTitle(QtGui.QApplication.translate("Form", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleZ_minus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleZ_plus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))

