# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\github\DEV_pymel\00_wip\SmartRig\ManageCtrls\manageCtrls_ui.ui'
#
# Created: Wed May 06 16:06:40 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(128, 91)
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.move_grp = QtGui.QGroupBox(Form)
        self.move_grp.setObjectName("move_grp")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.move_grp)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBox_2 = QtGui.QGroupBox(self.move_grp)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Xminus_pb = QtGui.QPushButton(self.groupBox_2)
        self.Xminus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Xminus_pb.setObjectName("Xminus_pb")
        self.horizontalLayout.addWidget(self.Xminus_pb)
        self.Xplus_pb = QtGui.QPushButton(self.groupBox_2)
        self.Xplus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Xplus_pb.setObjectName("Xplus_pb")
        self.horizontalLayout.addWidget(self.Xplus_pb)
        self.horizontalLayout_4.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.move_grp)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Yminus_pb = QtGui.QPushButton(self.groupBox_3)
        self.Yminus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Yminus_pb.setObjectName("Yminus_pb")
        self.horizontalLayout_2.addWidget(self.Yminus_pb)
        self.Yplus_pb = QtGui.QPushButton(self.groupBox_3)
        self.Yplus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Yplus_pb.setObjectName("Yplus_pb")
        self.horizontalLayout_2.addWidget(self.Yplus_pb)
        self.horizontalLayout_4.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.move_grp)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Zminus_pb = QtGui.QPushButton(self.groupBox_4)
        self.Zminus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Zminus_pb.setObjectName("Zminus_pb")
        self.horizontalLayout_3.addWidget(self.Zminus_pb)
        self.Zplus_pb = QtGui.QPushButton(self.groupBox_4)
        self.Zplus_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.Zplus_pb.setObjectName("Zplus_pb")
        self.horizontalLayout_3.addWidget(self.Zplus_pb)
        self.horizontalLayout_4.addWidget(self.groupBox_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.verticalLayout.addWidget(self.move_grp)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.scaleXYZ_pb = QtGui.QPushButton(self.groupBox)
        self.scaleXYZ_pb.setObjectName("scaleXYZ_pb")
        self.horizontalLayout_5.addWidget(self.scaleXYZ_pb)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.groupBox)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Controllers Manager", None, QtGui.QApplication.UnicodeUTF8))
        self.move_grp.setTitle(QtGui.QApplication.translate("Form", "Move:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.Xminus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Xplus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.Yminus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Yplus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.Zminus_pb.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.Zplus_pb.setText(QtGui.QApplication.translate("Form", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.scaleXYZ_pb.setText(QtGui.QApplication.translate("Form", "scale", None, QtGui.QApplication.UnicodeUTF8))

