# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'J:\GitHub_repo\DEV_pymel\00_wip\SmartRig\MyMayaScripts\UI_myMayaScripts.ui'
#
# Created: Thu May 28 10:48:00 2015
#      by: pyside-uic 0.2.14 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(345, 423)
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.French, QtCore.QLocale.France))
        self.verticalLayout_3 = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_17.setSpacing(2)
        self.verticalLayout_17.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 318, 552))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.helpTool_arrowL_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.helpTool_arrowL_tb.setEnabled(True)
        self.helpTool_arrowL_tb.setAutoRaise(True)
        self.helpTool_arrowL_tb.setArrowType(QtCore.Qt.RightArrow)
        self.helpTool_arrowL_tb.setObjectName("helpTool_arrowL_tb")
        self.horizontalLayout_11.addWidget(self.helpTool_arrowL_tb)
        self.helpTool_arrowD_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.helpTool_arrowD_tb.setAutoRaise(True)
        self.helpTool_arrowD_tb.setArrowType(QtCore.Qt.DownArrow)
        self.helpTool_arrowD_tb.setObjectName("helpTool_arrowD_tb")
        self.horizontalLayout_11.addWidget(self.helpTool_arrowD_tb)
        self.helpTool_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.helpTool_tb.setCheckable(True)
        self.helpTool_tb.setChecked(True)
        self.helpTool_tb.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.helpTool_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.helpTool_tb.setAutoRaise(True)
        self.helpTool_tb.setArrowType(QtCore.Qt.NoArrow)
        self.helpTool_tb.setObjectName("helpTool_tb")
        self.horizontalLayout_11.addWidget(self.helpTool_tb)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem)
        self.verticalLayout_4.addLayout(self.horizontalLayout_11)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.Panel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.helpersGrp = QtGui.QGroupBox(self.frame)
        self.helpersGrp.setObjectName("helpersGrp")
        self.gridLayout_2 = QtGui.QGridLayout(self.helpersGrp)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        self.colorGrp = QtGui.QGroupBox(self.helpersGrp)
        self.colorGrp.setObjectName("colorGrp")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.colorGrp)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.yellow_pb = QtGui.QPushButton(self.colorGrp)
        self.yellow_pb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.yellow_pb.setAutoDefault(False)
        self.yellow_pb.setObjectName("yellow_pb")
        self.horizontalLayout_5.addWidget(self.yellow_pb)
        self.red_pb = QtGui.QPushButton(self.colorGrp)
        self.red_pb.setEnabled(True)
        self.red_pb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.red_pb.setAutoDefault(False)
        self.red_pb.setObjectName("red_pb")
        self.horizontalLayout_5.addWidget(self.red_pb)
        self.blue_pb = QtGui.QPushButton(self.colorGrp)
        self.blue_pb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.blue_pb.setAutoDefault(False)
        self.blue_pb.setObjectName("blue_pb")
        self.horizontalLayout_5.addWidget(self.blue_pb)
        spacerItem2 = QtGui.QSpacerItem(22, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.gridLayout_2.addWidget(self.colorGrp, 2, 1, 1, 1)
        self.alias = QtGui.QGroupBox(self.helpersGrp)
        self.alias.setObjectName("alias")
        self.horizontalLayout_17 = QtGui.QHBoxLayout(self.alias)
        self.horizontalLayout_17.setSpacing(0)
        self.horizontalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.createAlias_pb = QtGui.QPushButton(self.alias)
        self.createAlias_pb.setObjectName("createAlias_pb")
        self.horizontalLayout_17.addWidget(self.createAlias_pb)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem3)
        self.gridLayout_2.addWidget(self.alias, 0, 1, 1, 1)
        self.groupsGrp = QtGui.QGroupBox(self.helpersGrp)
        self.groupsGrp.setObjectName("groupsGrp")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupsGrp)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.insertGrp_pb = QtGui.QPushButton(self.groupsGrp)
        self.insertGrp_pb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.insertGrp_pb.setAutoDefault(False)
        self.insertGrp_pb.setObjectName("insertGrp_pb")
        self.horizontalLayout_4.addWidget(self.insertGrp_pb)
        self.rootGrp_pb = QtGui.QPushButton(self.groupsGrp)
        self.rootGrp_pb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rootGrp_pb.setAutoDefault(False)
        self.rootGrp_pb.setObjectName("rootGrp_pb")
        self.horizontalLayout_4.addWidget(self.rootGrp_pb)
        self.childGrp_pb = QtGui.QPushButton(self.groupsGrp)
        self.childGrp_pb.setAutoDefault(False)
        self.childGrp_pb.setObjectName("childGrp_pb")
        self.horizontalLayout_4.addWidget(self.childGrp_pb)
        spacerItem4 = QtGui.QSpacerItem(7, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.gridLayout_2.addWidget(self.groupsGrp, 1, 1, 1, 1)
        self.LocGrp = QtGui.QGroupBox(self.helpersGrp)
        self.LocGrp.setObjectName("LocGrp")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.LocGrp)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.loc10_pb = QtGui.QPushButton(self.LocGrp)
        self.loc10_pb.setMaximumSize(QtCore.QSize(25, 16777215))
        self.loc10_pb.setAutoDefault(False)
        self.loc10_pb.setObjectName("loc10_pb")
        self.horizontalLayout_2.addWidget(self.loc10_pb)
        self.loc05_pb = QtGui.QPushButton(self.LocGrp)
        self.loc05_pb.setMaximumSize(QtCore.QSize(25, 16777215))
        self.loc05_pb.setAutoDefault(False)
        self.loc05_pb.setObjectName("loc05_pb")
        self.horizontalLayout_2.addWidget(self.loc05_pb)
        self.loc02_pb = QtGui.QPushButton(self.LocGrp)
        self.loc02_pb.setMaximumSize(QtCore.QSize(25, 16777215))
        self.loc02_pb.setAutoDefault(False)
        self.loc02_pb.setObjectName("loc02_pb")
        self.horizontalLayout_2.addWidget(self.loc02_pb)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addWidget(self.LocGrp, 1, 0, 1, 1)
        self.circlesGrp = QtGui.QGroupBox(self.helpersGrp)
        self.circlesGrp.setObjectName("circlesGrp")
        self.horizontalLayout = QtGui.QHBoxLayout(self.circlesGrp)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.circleX_pb = QtGui.QPushButton(self.circlesGrp)
        self.circleX_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.circleX_pb.setAutoDefault(False)
        self.circleX_pb.setObjectName("circleX_pb")
        self.horizontalLayout.addWidget(self.circleX_pb)
        self.circleY_pb = QtGui.QPushButton(self.circlesGrp)
        self.circleY_pb.setMinimumSize(QtCore.QSize(0, 0))
        self.circleY_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.circleY_pb.setAutoDefault(False)
        self.circleY_pb.setObjectName("circleY_pb")
        self.horizontalLayout.addWidget(self.circleY_pb)
        self.circleZ_pb = QtGui.QPushButton(self.circlesGrp)
        self.circleZ_pb.setMaximumSize(QtCore.QSize(20, 16777215))
        self.circleZ_pb.setAutoDefault(False)
        self.circleZ_pb.setObjectName("circleZ_pb")
        self.horizontalLayout.addWidget(self.circleZ_pb)
        spacerItem6 = QtGui.QSpacerItem(72, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout_2.addWidget(self.circlesGrp, 2, 0, 1, 1)
        self.controllerGrp = QtGui.QGroupBox(self.helpersGrp)
        self.controllerGrp.setObjectName("controllerGrp")
        self.verticalLayout_18 = QtGui.QVBoxLayout(self.controllerGrp)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.ctrlCube_pb = QtGui.QPushButton(self.controllerGrp)
        self.ctrlCube_pb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.ctrlCube_pb.setObjectName("ctrlCube_pb")
        self.horizontalLayout_13.addWidget(self.ctrlCube_pb)
        self.ctrlCross_pb = QtGui.QPushButton(self.controllerGrp)
        self.ctrlCross_pb.setMaximumSize(QtCore.QSize(40, 16777215))
        self.ctrlCross_pb.setObjectName("ctrlCross_pb")
        self.horizontalLayout_13.addWidget(self.ctrlCross_pb)
        self.strlSquare_pb = QtGui.QPushButton(self.controllerGrp)
        self.strlSquare_pb.setMaximumSize(QtCore.QSize(50, 16777215))
        self.strlSquare_pb.setObjectName("strlSquare_pb")
        self.horizontalLayout_13.addWidget(self.strlSquare_pb)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.verticalLayout_18.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.mergeControl_pb = QtGui.QPushButton(self.controllerGrp)
        self.mergeControl_pb.setObjectName("mergeControl_pb")
        self.horizontalLayout_14.addWidget(self.mergeControl_pb)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem8)
        self.verticalLayout_18.addLayout(self.horizontalLayout_14)
        self.gridLayout_2.addWidget(self.controllerGrp, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.helpersGrp)
        self.verticalLayout_4.addWidget(self.frame)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setSpacing(6)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.jointTool_arrowL_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.jointTool_arrowL_tb.setEnabled(True)
        self.jointTool_arrowL_tb.setAutoRaise(True)
        self.jointTool_arrowL_tb.setArrowType(QtCore.Qt.RightArrow)
        self.jointTool_arrowL_tb.setObjectName("jointTool_arrowL_tb")
        self.horizontalLayout_10.addWidget(self.jointTool_arrowL_tb)
        self.jointTool_arrowD_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.jointTool_arrowD_tb.setAutoRaise(True)
        self.jointTool_arrowD_tb.setArrowType(QtCore.Qt.DownArrow)
        self.jointTool_arrowD_tb.setObjectName("jointTool_arrowD_tb")
        self.horizontalLayout_10.addWidget(self.jointTool_arrowD_tb)
        self.jointTool_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.jointTool_tb.setCheckable(True)
        self.jointTool_tb.setChecked(True)
        self.jointTool_tb.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.jointTool_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.jointTool_tb.setAutoRaise(True)
        self.jointTool_tb.setArrowType(QtCore.Qt.NoArrow)
        self.jointTool_tb.setObjectName("jointTool_tb")
        self.horizontalLayout_10.addWidget(self.jointTool_tb)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem9)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.frame_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_2.setFrameShape(QtGui.QFrame.Panel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setLineWidth(2)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_12.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.joint_grp = QtGui.QGroupBox(self.frame_2)
        self.joint_grp.setObjectName("joint_grp")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.joint_grp)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_4 = QtGui.QGroupBox(self.joint_grp)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.jointSizeSel_rb1 = QtGui.QRadioButton(self.groupBox_4)
        self.jointSizeSel_rb1.setObjectName("jointSizeSel_rb1")
        self.horizontalLayout_9.addWidget(self.jointSizeSel_rb1)
        self.jointSizeSel_rb2 = QtGui.QRadioButton(self.groupBox_4)
        self.jointSizeSel_rb2.setChecked(True)
        self.jointSizeSel_rb2.setObjectName("jointSizeSel_rb2")
        self.horizontalLayout_9.addWidget(self.jointSizeSel_rb2)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtGui.QLabel(self.groupBox_4)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.jointSize_sb = QtGui.QDoubleSpinBox(self.groupBox_4)
        self.jointSize_sb.setDecimals(1)
        self.jointSize_sb.setSingleStep(0.1)
        self.jointSize_sb.setProperty("value", 1.0)
        self.jointSize_sb.setObjectName("jointSize_sb")
        self.horizontalLayout_3.addWidget(self.jointSize_sb)
        self.resizeJoint_pb = QtGui.QPushButton(self.groupBox_4)
        self.resizeJoint_pb.setAutoDefault(False)
        self.resizeJoint_pb.setObjectName("resizeJoint_pb")
        self.horizontalLayout_3.addWidget(self.resizeJoint_pb)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem11)
        self.verticalLayout_11.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.freezeOrient_pb = QtGui.QPushButton(self.joint_grp)
        self.freezeOrient_pb.setStyleSheet("")
        self.freezeOrient_pb.setAutoDefault(False)
        self.freezeOrient_pb.setObjectName("freezeOrient_pb")
        self.gridLayout.addWidget(self.freezeOrient_pb, 1, 2, 1, 1)
        self.lraOff_pb = QtGui.QPushButton(self.joint_grp)
        self.lraOff_pb.setAutoDefault(False)
        self.lraOff_pb.setObjectName("lraOff_pb")
        self.gridLayout.addWidget(self.lraOff_pb, 2, 1, 1, 1)
        self.showJoints_pb = QtGui.QPushButton(self.joint_grp)
        self.showJoints_pb.setAutoDefault(False)
        self.showJoints_pb.setObjectName("showJoints_pb")
        self.gridLayout.addWidget(self.showJoints_pb, 0, 1, 1, 1)
        self.lraOn_pb = QtGui.QPushButton(self.joint_grp)
        self.lraOn_pb.setAutoDefault(False)
        self.lraOn_pb.setObjectName("lraOn_pb")
        self.gridLayout.addWidget(self.lraOn_pb, 2, 0, 1, 1)
        self.hideOrient_pb = QtGui.QPushButton(self.joint_grp)
        self.hideOrient_pb.setAutoDefault(False)
        self.hideOrient_pb.setObjectName("hideOrient_pb")
        self.gridLayout.addWidget(self.hideOrient_pb, 1, 1, 1, 1)
        self.hideJoint_pb = QtGui.QPushButton(self.joint_grp)
        self.hideJoint_pb.setAutoDefault(False)
        self.hideJoint_pb.setObjectName("hideJoint_pb")
        self.gridLayout.addWidget(self.hideJoint_pb, 0, 0, 1, 1)
        self.showOrient_pb = QtGui.QPushButton(self.joint_grp)
        self.showOrient_pb.setAutoDefault(False)
        self.showOrient_pb.setObjectName("showOrient_pb")
        self.gridLayout.addWidget(self.showOrient_pb, 1, 0, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem12, 1, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.verticalLayout_12.addWidget(self.joint_grp)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.ikTool_arrowL_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.ikTool_arrowL_tb.setEnabled(True)
        self.ikTool_arrowL_tb.setAutoRaise(True)
        self.ikTool_arrowL_tb.setArrowType(QtCore.Qt.RightArrow)
        self.ikTool_arrowL_tb.setObjectName("ikTool_arrowL_tb")
        self.horizontalLayout_12.addWidget(self.ikTool_arrowL_tb)
        self.ikTool_arrowD_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.ikTool_arrowD_tb.setAutoRaise(True)
        self.ikTool_arrowD_tb.setArrowType(QtCore.Qt.DownArrow)
        self.ikTool_arrowD_tb.setObjectName("ikTool_arrowD_tb")
        self.horizontalLayout_12.addWidget(self.ikTool_arrowD_tb)
        self.ikTool_tb = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.ikTool_tb.setCheckable(True)
        self.ikTool_tb.setChecked(True)
        self.ikTool_tb.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.ikTool_tb.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.ikTool_tb.setAutoRaise(True)
        self.ikTool_tb.setArrowType(QtCore.Qt.NoArrow)
        self.ikTool_tb.setObjectName("ikTool_tb")
        self.horizontalLayout_12.addWidget(self.ikTool_tb)
        spacerItem13 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem13)
        self.verticalLayout_4.addLayout(self.horizontalLayout_12)
        self.frame_3 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame_3.setFrameShape(QtGui.QFrame.Panel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_3.setLineWidth(2)
        self.frame_3.setMidLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setSpacing(6)
        self.verticalLayout_8.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.ikTools_grp = QtGui.QGroupBox(self.frame_3)
        self.ikTools_grp.setObjectName("ikTools_grp")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.ikTools_grp)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.groupBox_8 = QtGui.QGroupBox(self.ikTools_grp)
        self.groupBox_8.setObjectName("groupBox_8")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.groupBox_8)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.dim_pb = QtGui.QPushButton(self.groupBox_8)
        self.dim_pb.setAutoDefault(False)
        self.dim_pb.setObjectName("dim_pb")
        self.horizontalLayout_7.addWidget(self.dim_pb)
        spacerItem14 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.verticalLayout_9.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.ikTools_grp)
        self.groupBox_9.setObjectName("groupBox_9")
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.groupBox_9)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.plane_pb = QtGui.QPushButton(self.groupBox_9)
        self.plane_pb.setAutoDefault(False)
        self.plane_pb.setObjectName("plane_pb")
        self.horizontalLayout_6.addWidget(self.plane_pb)
        self.ribbon_pb = QtGui.QPushButton(self.groupBox_9)
        self.ribbon_pb.setAutoDefault(False)
        self.ribbon_pb.setObjectName("ribbon_pb")
        self.horizontalLayout_6.addWidget(self.ribbon_pb)
        spacerItem15 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem15)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.verticalLayout_9.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.ikTools_grp)
        self.groupBox_10.setObjectName("groupBox_10")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.groupBox_10)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.groupBox_12 = QtGui.QGroupBox(self.groupBox_10)
        self.groupBox_12.setObjectName("groupBox_12")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.groupBox_12)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtGui.QLabel(self.groupBox_12)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.part_sb = QtGui.QSpinBox(self.groupBox_12)
        self.part_sb.setMinimum(1)
        self.part_sb.setObjectName("part_sb")
        self.horizontalLayout_8.addWidget(self.part_sb)
        self.arc_pb = QtGui.QPushButton(self.groupBox_12)
        self.arc_pb.setAutoDefault(False)
        self.arc_pb.setObjectName("arc_pb")
        self.horizontalLayout_8.addWidget(self.arc_pb)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem16)
        self.verticalLayout_16.addLayout(self.horizontalLayout_8)
        self.verticalLayout_14.addWidget(self.groupBox_12)
        self.verticalLayout_9.addWidget(self.groupBox_10)
        self.verticalLayout_8.addWidget(self.ikTools_grp)
        self.verticalLayout_4.addWidget(self.frame_3)
        spacerItem17 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem17)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_17.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.scrollArea_2 = QtGui.QScrollArea(self.tab_2)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 315, 373))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.FKGrp = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.FKGrp.setObjectName("FKGrp")
        self.horizontalLayout_15 = QtGui.QHBoxLayout(self.FKGrp)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.selectHierarchy_cb = QtGui.QCheckBox(self.FKGrp)
        self.selectHierarchy_cb.setObjectName("selectHierarchy_cb")
        self.horizontalLayout_15.addWidget(self.selectHierarchy_cb)
        self.createFK_pb = QtGui.QPushButton(self.FKGrp)
        self.createFK_pb.setObjectName("createFK_pb")
        self.horizontalLayout_15.addWidget(self.createFK_pb)
        self.FKanchor_cb = QtGui.QCheckBox(self.FKGrp)
        self.FKanchor_cb.setObjectName("FKanchor_cb")
        self.horizontalLayout_15.addWidget(self.FKanchor_cb)
        spacerItem18 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem18)
        self.verticalLayout_19.addWidget(self.FKGrp)
        self.ikfk_grp = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.ikfk_grp.setObjectName("ikfk_grp")
        self.verticalLayout = QtGui.QVBoxLayout(self.ikfk_grp)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.mirrorJnt_cb = QtGui.QCheckBox(self.ikfk_grp)
        self.mirrorJnt_cb.setObjectName("mirrorJnt_cb")
        self.horizontalLayout_18.addWidget(self.mirrorJnt_cb)
        self.ikfk_pb = QtGui.QPushButton(self.ikfk_grp)
        self.ikfk_pb.setObjectName("ikfk_pb")
        self.horizontalLayout_18.addWidget(self.ikfk_pb)
        self.IKFKanchor_cb = QtGui.QCheckBox(self.ikfk_grp)
        self.IKFKanchor_cb.setObjectName("IKFKanchor_cb")
        self.horizontalLayout_18.addWidget(self.IKFKanchor_cb)
        spacerItem19 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem19)
        self.verticalLayout.addLayout(self.horizontalLayout_18)
        self.revfoot_grp = QtGui.QGroupBox(self.ikfk_grp)
        self.revfoot_grp.setObjectName("revfoot_grp")
        self.horizontalLayout_16 = QtGui.QHBoxLayout(self.revfoot_grp)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.revFootMirror_cb = QtGui.QCheckBox(self.revfoot_grp)
        self.revFootMirror_cb.setObjectName("revFootMirror_cb")
        self.horizontalLayout_16.addWidget(self.revFootMirror_cb)
        self.revFoot_pb = QtGui.QPushButton(self.revfoot_grp)
        self.revFoot_pb.setObjectName("revFoot_pb")
        self.horizontalLayout_16.addWidget(self.revFoot_pb)
        spacerItem20 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem20)
        self.verticalLayout.addWidget(self.revfoot_grp)
        self.verticalLayout_19.addWidget(self.ikfk_grp)
        self.ikfkSpline_grp = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.ikfkSpline_grp.setObjectName("ikfkSpline_grp")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.ikfkSpline_grp)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.ikfkSpline_pb = QtGui.QPushButton(self.ikfkSpline_grp)
        self.ikfkSpline_pb.setObjectName("ikfkSpline_pb")
        self.horizontalLayout_19.addWidget(self.ikfkSpline_pb)
        self.IKFKspline_cb = QtGui.QCheckBox(self.ikfkSpline_grp)
        self.IKFKspline_cb.setObjectName("IKFKspline_cb")
        self.horizontalLayout_19.addWidget(self.IKFKspline_cb)
        spacerItem21 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem21)
        self.verticalLayout_2.addLayout(self.horizontalLayout_19)
        self.verticalLayout_19.addWidget(self.ikfkSpline_grp)
        spacerItem22 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem22)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_20.addWidget(self.scrollArea_2)
        self.tabWidget.addTab(self.tab_2, "")
        self.verticalLayout_3.addWidget(self.tabWidget)
        self.actionCoucou = QtGui.QAction(Dialog)
        self.actionCoucou.setCheckable(True)
        self.actionCoucou.setObjectName("actionCoucou")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.jointTool_tb, QtCore.SIGNAL("clicked(bool)"), self.joint_grp.setVisible)
        QtCore.QObject.connect(self.ikTool_tb, QtCore.SIGNAL("clicked(bool)"), self.ikTools_grp.setVisible)
        QtCore.QObject.connect(self.helpTool_arrowD_tb, QtCore.SIGNAL("clicked()"), self.helpTool_tb.click)
        QtCore.QObject.connect(self.helpTool_arrowL_tb, QtCore.SIGNAL("clicked()"), self.helpTool_tb.click)
        QtCore.QObject.connect(self.jointTool_arrowD_tb, QtCore.SIGNAL("clicked()"), self.jointTool_tb.click)
        QtCore.QObject.connect(self.jointTool_arrowL_tb, QtCore.SIGNAL("clicked()"), self.jointTool_tb.click)
        QtCore.QObject.connect(self.ikTool_arrowD_tb, QtCore.SIGNAL("clicked()"), self.ikTool_tb.click)
        QtCore.QObject.connect(self.ikTool_arrowL_tb, QtCore.SIGNAL("clicked()"), self.ikTool_tb.click)
        QtCore.QObject.connect(self.helpTool_tb, QtCore.SIGNAL("clicked(bool)"), self.helpTool_arrowD_tb.setVisible)
        QtCore.QObject.connect(self.helpTool_tb, QtCore.SIGNAL("clicked(bool)"), self.helpTool_arrowL_tb.setHidden)
        QtCore.QObject.connect(self.jointTool_tb, QtCore.SIGNAL("clicked(bool)"), self.jointTool_arrowD_tb.setVisible)
        QtCore.QObject.connect(self.jointTool_tb, QtCore.SIGNAL("clicked(bool)"), self.jointTool_arrowL_tb.setHidden)
        QtCore.QObject.connect(self.ikTool_tb, QtCore.SIGNAL("clicked(bool)"), self.ikTool_arrowD_tb.setVisible)
        QtCore.QObject.connect(self.ikTool_tb, QtCore.SIGNAL("clicked(bool)"), self.ikTool_arrowL_tb.setHidden)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "My Maya Scripts", None, QtGui.QApplication.UnicodeUTF8))
        self.helpTool_arrowL_tb.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.helpTool_arrowD_tb.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.helpTool_tb.setText(QtGui.QApplication.translate("Dialog", "Helpers Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.helpersGrp.setTitle(QtGui.QApplication.translate("Dialog", "Helpers:", None, QtGui.QApplication.UnicodeUTF8))
        self.colorGrp.setTitle(QtGui.QApplication.translate("Dialog", "Colors:", None, QtGui.QApplication.UnicodeUTF8))
        self.yellow_pb.setText(QtGui.QApplication.translate("Dialog", "yellow", None, QtGui.QApplication.UnicodeUTF8))
        self.red_pb.setText(QtGui.QApplication.translate("Dialog", "red", None, QtGui.QApplication.UnicodeUTF8))
        self.blue_pb.setText(QtGui.QApplication.translate("Dialog", "blue", None, QtGui.QApplication.UnicodeUTF8))
        self.alias.setTitle(QtGui.QApplication.translate("Dialog", "create alias:", None, QtGui.QApplication.UnicodeUTF8))
        self.createAlias_pb.setText(QtGui.QApplication.translate("Dialog", "create alias", None, QtGui.QApplication.UnicodeUTF8))
        self.groupsGrp.setTitle(QtGui.QApplication.translate("Dialog", "Groups:", None, QtGui.QApplication.UnicodeUTF8))
        self.insertGrp_pb.setText(QtGui.QApplication.translate("Dialog", "Insert ", None, QtGui.QApplication.UnicodeUTF8))
        self.rootGrp_pb.setToolTip(QtGui.QApplication.translate("Dialog", "parent the selected object to a group, under the world. Break hierarchy if necessary.", None, QtGui.QApplication.UnicodeUTF8))
        self.rootGrp_pb.setText(QtGui.QApplication.translate("Dialog", "Root ", None, QtGui.QApplication.UnicodeUTF8))
        self.childGrp_pb.setToolTip(QtGui.QApplication.translate("Dialog", "insert group in hierarchy, as parent of the selected object", None, QtGui.QApplication.UnicodeUTF8))
        self.childGrp_pb.setText(QtGui.QApplication.translate("Dialog", "Child ", None, QtGui.QApplication.UnicodeUTF8))
        self.LocGrp.setTitle(QtGui.QApplication.translate("Dialog", "Create Locator:", None, QtGui.QApplication.UnicodeUTF8))
        self.loc10_pb.setText(QtGui.QApplication.translate("Dialog", "1.0", None, QtGui.QApplication.UnicodeUTF8))
        self.loc05_pb.setText(QtGui.QApplication.translate("Dialog", "0.5", None, QtGui.QApplication.UnicodeUTF8))
        self.loc02_pb.setText(QtGui.QApplication.translate("Dialog", "0.2", None, QtGui.QApplication.UnicodeUTF8))
        self.circlesGrp.setTitle(QtGui.QApplication.translate("Dialog", "Create Circle Controller:", None, QtGui.QApplication.UnicodeUTF8))
        self.circleX_pb.setText(QtGui.QApplication.translate("Dialog", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.circleY_pb.setText(QtGui.QApplication.translate("Dialog", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.circleZ_pb.setText(QtGui.QApplication.translate("Dialog", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.controllerGrp.setTitle(QtGui.QApplication.translate("Dialog", "Controller Shape :", None, QtGui.QApplication.UnicodeUTF8))
        self.ctrlCube_pb.setText(QtGui.QApplication.translate("Dialog", "cube", None, QtGui.QApplication.UnicodeUTF8))
        self.ctrlCross_pb.setText(QtGui.QApplication.translate("Dialog", "cross", None, QtGui.QApplication.UnicodeUTF8))
        self.strlSquare_pb.setText(QtGui.QApplication.translate("Dialog", "square", None, QtGui.QApplication.UnicodeUTF8))
        self.mergeControl_pb.setText(QtGui.QApplication.translate("Dialog", "replace controllers shape", None, QtGui.QApplication.UnicodeUTF8))
        self.jointTool_arrowL_tb.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.jointTool_arrowD_tb.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.jointTool_tb.setText(QtGui.QApplication.translate("Dialog", "Joint Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.joint_grp.setTitle(QtGui.QApplication.translate("Dialog", "Joints:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Dialog", "Resize Joints:", None, QtGui.QApplication.UnicodeUTF8))
        self.jointSizeSel_rb1.setText(QtGui.QApplication.translate("Dialog", "Selection", None, QtGui.QApplication.UnicodeUTF8))
        self.jointSizeSel_rb2.setText(QtGui.QApplication.translate("Dialog", "All", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Joints Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.resizeJoint_pb.setText(QtGui.QApplication.translate("Dialog", "Resize Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.freezeOrient_pb.setText(QtGui.QApplication.translate("Dialog", "Freeze Orient", None, QtGui.QApplication.UnicodeUTF8))
        self.lraOff_pb.setText(QtGui.QApplication.translate("Dialog", "LRA off", None, QtGui.QApplication.UnicodeUTF8))
        self.showJoints_pb.setText(QtGui.QApplication.translate("Dialog", "Show All Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.lraOn_pb.setText(QtGui.QApplication.translate("Dialog", "LRA on", None, QtGui.QApplication.UnicodeUTF8))
        self.hideOrient_pb.setText(QtGui.QApplication.translate("Dialog", "Hide Orient", None, QtGui.QApplication.UnicodeUTF8))
        self.hideJoint_pb.setText(QtGui.QApplication.translate("Dialog", "Hide All Joints", None, QtGui.QApplication.UnicodeUTF8))
        self.showOrient_pb.setText(QtGui.QApplication.translate("Dialog", "Show Orient", None, QtGui.QApplication.UnicodeUTF8))
        self.ikTool_arrowL_tb.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ikTool_arrowD_tb.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.ikTool_tb.setText(QtGui.QApplication.translate("Dialog", "IK Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.ikTools_grp.setTitle(QtGui.QApplication.translate("Dialog", "IK Tools:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("Dialog", "Dimensions:", None, QtGui.QApplication.UnicodeUTF8))
        self.dim_pb.setText(QtGui.QApplication.translate("Dialog", "create distance system", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Dialog", "Ribbon:", None, QtGui.QApplication.UnicodeUTF8))
        self.plane_pb.setText(QtGui.QApplication.translate("Dialog", "make Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.ribbon_pb.setText(QtGui.QApplication.translate("Dialog", "make Ribbon", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_10.setTitle(QtGui.QApplication.translate("Dialog", "IK Spline:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_12.setTitle(QtGui.QApplication.translate("Dialog", "Sections:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "parts", None, QtGui.QApplication.UnicodeUTF8))
        self.arc_pb.setText(QtGui.QApplication.translate("Dialog", "create arcLenght", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Dialog", "Misc", None, QtGui.QApplication.UnicodeUTF8))
        self.FKGrp.setTitle(QtGui.QApplication.translate("Dialog", "FK Chain:", None, QtGui.QApplication.UnicodeUTF8))
        self.selectHierarchy_cb.setText(QtGui.QApplication.translate("Dialog", "Select hierarchy", None, QtGui.QApplication.UnicodeUTF8))
        self.createFK_pb.setText(QtGui.QApplication.translate("Dialog", "Create FKChain", None, QtGui.QApplication.UnicodeUTF8))
        self.FKanchor_cb.setText(QtGui.QApplication.translate("Dialog", "Anchor", None, QtGui.QApplication.UnicodeUTF8))
        self.ikfk_grp.setTitle(QtGui.QApplication.translate("Dialog", "IKFK:", None, QtGui.QApplication.UnicodeUTF8))
        self.mirrorJnt_cb.setText(QtGui.QApplication.translate("Dialog", "Mirrored Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.ikfk_pb.setText(QtGui.QApplication.translate("Dialog", "create IKFK", None, QtGui.QApplication.UnicodeUTF8))
        self.IKFKanchor_cb.setText(QtGui.QApplication.translate("Dialog", "Anchor", None, QtGui.QApplication.UnicodeUTF8))
        self.revfoot_grp.setTitle(QtGui.QApplication.translate("Dialog", "Reverse Foot:", None, QtGui.QApplication.UnicodeUTF8))
        self.revFootMirror_cb.setText(QtGui.QApplication.translate("Dialog", "Mirrored Joint", None, QtGui.QApplication.UnicodeUTF8))
        self.revFoot_pb.setText(QtGui.QApplication.translate("Dialog", "create reverse foot", None, QtGui.QApplication.UnicodeUTF8))
        self.ikfkSpline_grp.setTitle(QtGui.QApplication.translate("Dialog", "IKFK spline:", None, QtGui.QApplication.UnicodeUTF8))
        self.ikfkSpline_pb.setText(QtGui.QApplication.translate("Dialog", "create IKFK spline", None, QtGui.QApplication.UnicodeUTF8))
        self.IKFKspline_cb.setText(QtGui.QApplication.translate("Dialog", "Anchor", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Dialog", "FK/IK", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoucou.setText(QtGui.QApplication.translate("Dialog", "coucou", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCoucou.setToolTip(QtGui.QApplication.translate("Dialog", "action couou", None, QtGui.QApplication.UnicodeUTF8))

